version: "3.7"
services:
  # rmq:
  #   image: rabbitmq
  #   container_name: rabbitmq-server
  #   hostname: rabbitmq-server
  #   ports:
  #     - "5672:5672"
  s1:
    build:
      context: .
      dockerfile: Dockerfile.s1
    depends_on:
      - rmq
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  s2:
    build:
      context: .
      dockerfile: Dockerfile.s2
    depends_on:
      - s1
